### PR TITLE
docs: update browsers.md

### PR DESCRIPTION
**Pull request by uncenter**
This PR updates `docs/browsers.md` to use the new GitHub callout syntax, `[!NOTE]` (sorry I missed this file earlier!) and corrects the syntax for the browsers table.

### CODE REVIEW

**Review by isabelroses — APPROVED** [review]

**Comment by uncenter** [comment]
Is it worth adding `arc://version/` for Arc in this PR actually?

**Comment by isabelroses** [comment]
> Is it worth adding `arc://version/` for Arc in this PR actually?

If Arc is compatible with the stylus extension and its not Chromium based etc, i don't see why not

**Comment by uncenter** [comment]
> > Is it worth adding `arc://version/` for Arc in this PR actually?
> 
> If Arc is compatible with the stylus extension and its not Chromium based etc, i don't see why not

I'm using Arc right now! It is Chromium-based but some people... might not know that.

**Comment by isabelroses** [comment]
> I'm using Arc with Stylus right now! It is Chromium-based but... some people might not know that.

Im happy for it to be added, then

**Review by isabelroses — APPROVED** [review]

**Pull request merged**
