### PR TITLE
refactor(tree-wide): prefer simpler method for theming `<img>` elements

### PR DESCRIPTION
**Pull request by uncenter**
See https://github.com/catppuccin/userstyles/issues/449#issuecomment-2007738722. The Stylus wiki lied to me. 😢

### CODE REVIEW

**Review by isabelroses — APPROVED** [review]
🚀 looks a lot better and easier to use.

**Comment by uncenter** [comment]
> 🚀 looks a lot better and easier to use.

Definitely ahah. I've tested the npm, GitHub, and ChatGPT userstyles. Please make sure to check all the locations of the SVGs that have been changed to make sure everything is still working :)

**Comment by uncenter** [comment]
> 🚀 looks a lot better and easier to use.

Oh and thanks to @GitMuslim for showing me this! We already use this technique in some of their userstyles (Google, Minesweeper Online).

**Comment by isabelroses** [comment]
> > 🚀 looks a lot better and easier to use.
> 
> Definitely ahah. I've tested the npm, GitHub, and ChatGPT userstyles. Please make sure to check all the locations of the SVGs that have been changed to make sure everything is still working :)

I check for youtube and github, those are the only ones i have easy access to.

**Comment by uncenter** [comment]
PyPI looks good as well. I think its safe to merge seeing as none of those are causing any issues?

**Comment by isabelroses** [comment]
> PyPI looks good as well. I think its safe to merge seeing as none of those are causing any issues?

Sounds good, but I'd like at least 1 more reviewer just to be sure.

**Review by trinkey — APPROVED** [review]

**Review by GenShibe — APPROVED** [review]
LGTM, thanks for making it simpler!

**Pull request merged**
