### PR TITLE
refactor(snapchat): rewrite

### PR DESCRIPTION
**Pull request by UnbelievablyNoah**
## 🔧 What does this fix? 🔧

Almost full rewrite of the Snapchat theme, has options for enabling/disabling scrollbar, hiding/showing the story section and notifications, plus a more up to date and cleaner looking version of the theme. 

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [contributing guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/CONTRIBUTING.md).
- [X] I have updated the version appropriately in the `==UserStyle==` header of the `catppuccin.user.css` file.

### CODE REVIEW

**Review by isabelroses — CHANGES_REQUESTED** [review]
Ideally we want to avoid opinionated changes like this, in our repo, we would prefer to keep all our changes to only the colours and additional changes such as these to be brought in by their own respective userstyles.

This is also why our linter is providing warnings on css like:
> border: 1px solid var(--sigDivider) !important;

**Comment by itzTheMeow** [comment]
I'm not sure if this is a repo-wide thing but I avoided using the generated class names like `wHvEy` because they could change in the future and break the theme.

**Comment by itzTheMeow** [comment]
Also the icon colorizations were removed?
image

these buttons aren't themed anymore
image
image

the shadows on the avatars block out people in the background:
old:
image
new:
image

also page layout shifts when enabling the theme:
before:
image
after:
image

before:
image
after:
image

**Comment by isabelroses** [comment]
Hello, its been over a month without any notable changes to the state of this PR. Therefore, I am going to close it as stale, If you change your mind about the changes we requested please reopen the PR and make the appropriate changes. Thank you for your time and effort.

**Pull request closed without merging**
