### PR TITLE
feat(treewide): add require-color-op-func-percentage stylelint rule

### PR DESCRIPTION
**Pull request by uncenter**
Adds a new rule, `require-color-op-func-percentage`, that requires the "amount" argument to [color operation](https://lesscss.org/functions/#color-operations) functions (e.g. `fade(<color>, <amount>)`) to be in percentage format - `<float or int>%`. This consistency makes these functions more readable, and can catch bugs. As you can see in the diff, there are many cases of `fadeout(@text, 0.8)`; people may think this 0.8 is out of 1, meaning 80%, but it is really just 0.8% (https://lesscss.org/less-preview/#eyJjb2RlIjoiYSB7XG4gIGNvbG9yOiBmYWRlb3V0KCMwMDAwMDAsIDAuOCk7XG59IiwiYWN0aXZlVmVyc2lvbiI6IjQuMi4wIiwibWF0aCI6InBhcmVucy1kaXZpc2lvbiIsInN0cmljdFVuaXRzIjpmYWxzZX0=). These very very tiny percentages should be corrected at some point as well.

### CODE REVIEW

**Review by r58Playz — DISMISSED** [review]

**Review by comfysage — APPROVED** [review]

**Review by GenShibe — DISMISSED** [review]

**Review by trinkey — CHANGES_REQUESTED** [review]
0.5 should be 50%, not 0.5%

**Comment by uncenter** [comment]
> 0.8 should be 80% though? without a percent sign, the number is on a 0-1 scale instead of 0-100

> this may not be how less apparently does it but it is likely everyone's intention

Right, as I said in my original comment:

> there are many cases of `fadeout(@text, 0.8)`; people may think this 0.8 is out of 1, meaning 80%, but it is really just 0.8%

I linked to a Less playground where you can see that 0.8 results in a very small (difference?); I'll make it even clearer here:

https://lesscss.org/less-preview/#eyJjb2RlIjoiYSB7XG4gIGNvbG9yOiBmYWRlb3V0KCMwMDAwMDAsIDAuOCk7XG4gIGJhY2tncm91bmQ6IGZhZGVvdXQoIzAwMDAwMCwgODAlKVxufSIsImFjdGl2ZVZlcnNpb24iOiI0LjIuMCIsIm1hdGgiOiJwYXJlbnMtZGl2aXNpb24iLCJzdHJpY3RVbml0cyI6ZmFsc2V9

> 0.5 should be 50%, not 0.5%

This will be done in a followup PR, I have no intention of going through and fixing all these issues on individual styles. If the maintainers of the following userstyles could please make follow up PRs correcting this issues:

- youtube
- whatsapp-web
- trinket
- snapchat-web
- lastfm
- ichi.moe
- hoppscotch

**Review by isabelroses — DISMISSED** [review]

**Review by trinkey — DISMISSED** [review]
remind me to make a fix pr for trinket when this gets merged

**Comment by uncenter** [comment]
Discussed a little in Discord, so just to clarify: this change causes no changes to the compiled output of the userstyles. Any bugs you can now easily see like `0.8` not being `80%` have already existed and still exist.

That being said, @isabelroses raised the point of should this lint rule automatically interpret the input and if it is less than 1, assume the author intentions and change it to the (hopefully) intended `80%` instead of just `0.8%`. 

Maintainers, if we could do a little poll just leave a thumbs up 👍  on this comment if I should change it to interpret the result (basically remove these bugs) or a thumbs down 👎 if I should leave it as is.

^^ Also interesting to note here, if I did change it (👍 vote) that would mean these userstyles would actually look different. Maybe I'll do that and maintainers you can check out the areas where percents were changed to make sure it still looks fine?

**Review by itzTheMeow — DISMISSED** [review]

**Comment by uncenter** [comment]
With an overwhelming unanimous vote, looks like we want an autofix! Implemented now :)

**Comment by uncenter** [comment]
I'm going to assume approvals here on out include a visual review of the website after updating the userstyle from this PR if you maintain an individual userstyle - please ensure nothing now looks wrong because of this!

**Review by isabelroses — APPROVED** [review]
Amazing work!

**Review by sgoudham — APPROVED** [review]
ig

**Review by trinkey — APPROVED** [review]
lgtm

**Comment by AnubisNekhet** [comment]
lgtm

**Review by AnubisNekhet — APPROVED** [review]

**Pull request merged**
