### PR TITLE
feat(twitter): init

### PR DESCRIPTION
**Pull request by watatomo**
## 🎉 Theme for [Twitter](https://twitter.com) 🎉

Soothing pastel theme for Twitter.

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [submission guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/userstyle-creation.md).
- [x] I have made a new directory underneath `/styles/<name-of-website>` containing the contents of the [`/template`](https://github.com/catppuccin/userstyles/blob/main/template/) directory.
  - [x] I have ensured that the new directory is in **lower-kebab-case**.
  - [x] I have followed the template and kept the preprocessor as [LESS](https://lesscss.org/#overview).
- [x] I have made sure to update the
      [`userstyles.yml`](https://github.com/catppuccin/userstyles/blob/main/src/userstyles.yml)
      file with information about the new userstyle.
- [x] I have included the following files:
  - `catppuccin.user.css` - all the CSS for the userstyle, based on the
    template.
  - `assets/mocha.webp`, `assets/macchiato.webp`, `assets/frappe.webp` and
    `assets/latte.webp` - individual screenshots of the themed website, in all 4
    Catppuccin flavors.
  - `catwalk.webp` - image of all individual screenshots stitched together,
    generated via [catwalk](https://github.com/catppuccin/toolbox#-catwalk).

### CODE REVIEW

**Comment by uncenter** [comment]
Other than the commented out parts (template at the bottom, unsupported thingy towards the top) it looks fine. I think we usually do both light and dark though, but you can just do it based on media queries.

**Review by uncenter — COMMENTED** [review]
Code looks good, checking it out visually now...

**Review by uncenter — CHANGES_REQUESTED** [review]
One little last thing, looks spectacular otherwise.

Input placeholder text is unthemed (see https://developer.mozilla.org/en-US/docs/Web/CSS/::placeholder):
Screenshot 2024-02-05 at 22 49 30 (Arc)

**Review by uncenter — APPROVED** [review]
LGTM, just fix the lint issues and it should be all set.

**Review by isabelroses — APPROVED** [review]
Amazing job, looks beautiful.

Edit: after confirming by using for a few extra hours, I can confirm we're good to go.

**Pull request merged**
