### PR TITLE
feat(pinterest): init

### PR DESCRIPTION
**Pull request by jn-sena**
## 🎉 Theme for [Pinterest](https://www.pinterest.com) 🎉

An image sharing and social media platform in the form of pinboards.

## 💬 Additional Comments 💬

Catwalk preview.

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [submission guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/userstyle-creation.md).
- [x] I have made a new directory underneath `/styles/<name-of-website>` containing the contents of the [`/template`](https://github.com/catppuccin/userstyles/blob/main/template/) directory.
  - [x] I have ensured that the new directory is in **lower-kebab-case**.
  - [x] I have followed the template and kept the preprocessor as [LESS](https://lesscss.org/#overview).
- [x] I have made sure to update the
      [`userstyles.yml`](https://github.com/catppuccin/userstyles/blob/main/src/userstyles.yml)
      file with information about the new userstyle.
- [x] I have included the following files:
  - `catppuccin.user.css` - all the CSS for the userstyle, based on the
    template.
  - `assets/mocha.webp`, `assets/macchiato.webp`, `assets/frappe.webp` and
    `assets/latte.webp` - individual screenshots of the themed website, in all 4
    Catppuccin flavors.
  - `catwalk.webp` - image of all individual screenshots stitched together,
    generated via [catwalk](https://github.com/catppuccin/toolbox#-catwalk).

### CODE REVIEW

**Review by isabelroses — CHANGES_REQUESTED** [review]
The [create page](https://www.pinterest.co.uk/pin-creation-tool/) is a bit hard to read:
image
And the settings pages as a whole have a few issues here and there
Otherwise good job this is an amazing port.

**Comment by jn-sena** [comment]
I've themed all the inputs in the settings page now, also fixed the about page before login just in case.

The inputs on the create page are greyed-out by default on Pinterest, as you can't edit them before uploading an image. They'll be normal after you upload something.

Thank you for your review!!

**Review by isabelroses — CHANGES_REQUESTED** [review]
Just noticed the contrast on the pronouns is a bit difficult 
image
And the birthday selection is a bit hard to read too
image

**Review by isabelroses — APPROVED** [review]
Thanks for your hard work.

**Pull request merged**
