### PR TITLE
feat(lingva): init

### PR DESCRIPTION
**Pull request by rubyowo**
## 💬 Additional Comments 💬
Alternative front-end for Google Translate, serving as a Free and Open Source translator with over a hundred languages available

The logo needs to be themed.

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [submission guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/userstyle-creation.md).
- [x] I have made a new directory underneath `/styles/<name-of-website>` containing the contents of the [`/template`](https://github.com/catppuccin/userstyles/blob/main/template/) directory.
  - [x] I have ensured that the new directory is in **lower-kebab-case**.
  - [x] I have followed the template and kept the preprocessor as [LESS](https://lesscss.org/#overview).
- [x] I have made sure to update the
      [`userstyles.yml`](https://github.com/catppuccin/userstyles/blob/main/src/userstyles.yml)
      file with information about the new userstyle.
- [x] I have included the following files:
  - `catppuccin.user.css` - all the CSS for the userstyle, based on the
    template.
  - `assets/mocha.webp`, `assets/macchiato.webp`, `assets/frappe.webp` and
    `assets/latte.webp` - individual screenshots of the themed website, in all 4
    Catppuccin flavors.
  - `catwalk.webp` - image of all individual screenshots stitched together,
    generated via [catwalk](https://github.com/catppuccin/toolbox#-catwalk).

### CODE REVIEW

**Comment by rubyowo** [comment]
I seem to have forgotten the catwalk 💀

**Comment by uncenter** [comment]
@nekowinston something about the latest release of nekowinston/setup-deno isn't working here.
Screenshot 2023-12-20 at 05 53 31 (Arc)

**Comment by nekowinston** [comment]
Thanks for the ping, sorry that my CI failed to catch that.
Should be fixed with the latest release of the action.

**Comment by isabelroses** [comment]
LGTM

**Pull request merged**
