### PR TITLE
fix(youtube): misc

### PR DESCRIPTION
**Pull request by somerand0mcat**
## 🔧 What does this fix? 🔧
as said in the title
## 🗒 Checklist 🗒

- [X] I have read and followed Catppuccin's [contributing guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/CONTRIBUTING.md).
- [X] I have updated the version appropriately in the `==UserStyle==` header of the `catppuccin.user.css` file.

### CODE REVIEW

**Comment by uncenter** [comment]
I'm going to leave this open for the next week. Feel free to put any additional fixes in this pull request and we can update the title appropriately. I'm tired of reviewing/merging 4 of your YouTube PRs a week.

**Comment by somerand0mcat** [comment]
> I'm going to leave this open for the next week. Feel free to put any additional fixes in this pull request and we can update the title appropriately. I'm tired of reviewing/merging 4 of your YouTube PRs a week.

@uncenter can i update the version to ``4.3.0`` just incase if this PR fixes a bunch of stuff?

**Comment by uncenter** [comment]
`style` is the conventional commit type for stylistic changes. Use `fix` or `feat`.

**Comment by somerand0mcat** [comment]
i think im going to close this pull request because theres alot of bugs on youtube/yt studio that takes a really long time to fix, also difficult to code too

**Comment by somerand0mcat** [comment]
>  I'm tired of reviewing/merging 4 of your YouTube PRs a week.
im tired of having to fix a bunch of bugs too
i made like 8 branches just for this single userstyle

**Comment by uncenter** [comment]
> of having to fix a bunch of bugs too
You don't have to do anything. We appreciate your contributions but don't feel pressured.

> i made like 8 branches just for this single userstyle

I saw! Hence why I suggested this miscellaneous fixes PR.

**Pull request closed without merging**
