### PR TITLE
refactor(nitter)!: delete

### PR DESCRIPTION
**Pull request by isabelroses**
closes https://github.com/catppuccin/userstyles/issues/1203

### CODE REVIEW

**Comment by thismoon** [comment]
But [xcancel](https://xcancel.com) still works

**Review by AnubisNekhet — APPROVED** [review]

**Comment by uncenter** [comment]
@thismoon can you find a list / check how many instances are (still) online?

**Comment by thismoon** [comment]
https://farside.link/ checks for working nitter instances every 5 minutes. There are 3 working instances currently but the last time I tried the other two they get rate limited after some use. xcancel doesn't, probably because it has a "Verifying your request" screen when you visit it for the first time.

**Comment by uncenter** [comment]
I think if we still have instances running and possibly using them, we'll keep nitter in for now. Closing this, leaving the issue open.

**Pull request closed without merging**
