### PR TITLE
fix(mastodon): contrast issues and misc

### PR DESCRIPTION
**Pull request by comfysage**
## 🔧 What does this fix? 🔧

fixed column-header button icon foreground color to use overlay2 (previously used mastodon default styling).

###### screenshots

(left button is hovered)

before:
before-image

after:
after-image

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [contributing guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/CONTRIBUTING.md).
- [x] I have updated the version appropriately in the `==UserStyle==` header of the `catppuccin.user.css` file.

### CODE REVIEW

**Comment by comfysage** [comment]
additional fix: fix boost icon color
override the svg fill colors to use ctp styling.

before:
before-image

after:
after-image

**Comment by comfysage** [comment]
additional fix: fix compose text-area contrast
the background color on the compose area was previously to light which made it difficult to read the text.

before:
before-image

after:
after-image

**Comment by comfysage** [comment]
additional fix: fix search popout text colors
some of the ui elements in the search popout were not using ctp colors or made reading difficult.

before:
before-image

after:
after-image

**Comment by comfysage** [comment]
additional fix: active and hovered leaf foreground colors
the active and hovered leaves in the admin view were not styled correctly.

before:
before-image

after:
after-image

**Comment by uncenter** [comment]
Converting to draft to let you accumulate more fixes, just mark it as ready once you are good to merge this one and I'll take a look.

**Review by isabelroses — CHANGES_REQUESTED** [review]
Its been about 2 weeks now so time to review!

Only one real concern from me. Is it possible to reduce the brightness of the hover here on the users page, i think surface0 or 1 would be better then the current surface2.
image

**Comment by comfysage** [comment]
> Its been about 2 weeks now so time to review!
> 
> Only one real concern from me. Is it possible to reduce the brightness of the hover here on the users page, i think surface0 or 1 would be better then the current surface2. image

here ya go! i fixed it real quick.

after:
fixup-image

**Review by isabelroses — APPROVED** [review]

**Review by uncenter — APPROVED** [review]

**Pull request merged**
