### PR TITLE
feat(pythonanywhere): init

### PR DESCRIPTION
**Pull request by trinkey**
## 🎉 Theme for PythonAnywhere 🎉

A website that lets you run code and host python servers online

## 💬 Additional Comments 💬

there's so many pngs

this also concludes a port request

## 🗒 Checklist 🗒

- [X] I have read and followed Catppuccin's [submission guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/userstyle-creation.md).
- [ ] I have made a new directory underneath `/styles/<name-of-website>` containing the contents of the [`/template`](https://github.com/catppuccin/userstyles/blob/main/template/) directory.
  - [X] I have ensured that the new directory is in **lower-kebab-case**.
  - [X] I have followed the template and kept the preprocessor as [LESS](https://lesscss.org/#overview).
- [X] I have made sure to update the
      [`userstyles.yml`](https://github.com/catppuccin/userstyles/blob/main/scripts/userstyles.yml)
      file with information about the new userstyle.
- [ ] I have included the following files:
  - `catppuccin.user.css` - all the CSS for the userstyle, based on the
    template.
  - `preview.webp` - composite image of all four individual flavor screenshots stitched together,
    generated via [Catwalk](https://github.com/catppuccin/toolbox/tree/main/catwalk#readme).

### CODE REVIEW

**Comment by trinkey** [comment]
linter is only complaining because i didn't make the preview yet

**Comment by trinkey** [comment]
i probably won't be able to finish this for a while because all browser-based applications (vscode, discord, firefox, chrome, etc) on my computer (windows and linux) crash within 5 minutes of booting up and require me to restart my computer every time so painnnnnnnnnnnnnnnn

**Comment by trinkey** [comment]
im like 80% sure it has something to do with my ram and i really hope it is because that's the only thing i have a replacement for if its any other hardware part im screwed

**Comment by trinkey** [comment]
dang it i fixed it now i don't have an excuse to procrastinating making svgs

**Comment by sgoudham** [comment]
As specified in https://github.com/catppuccin/catppuccin/discussions/2339, the original author no longer wants to finish the implementation and therefore I'll be closing this PR.

Others are encouraged to raise a new PR if they want to see this website themed.

**Pull request closed without merging**
