### PR TITLE
chore(tree-wide): change default accent color to mauve

### PR DESCRIPTION
**Pull request by uncenter**
## 🔧 What does this fix? 🔧

Changes the default accent color to mauve. Not sure if we should update versions here?

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [contributing guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/CONTRIBUTING.md).
- [x] I have updated the version appropriately in the `==UserStyle==` header of the `catppuccin.user.css` file.

### CODE REVIEW

**Review by Tnixc — APPROVED** [review]

**Review by Nyatalieeee — APPROVED** [review]

**Comment by nekowinston** [comment]
you guys got there in the end https://github.com/catppuccin/userstyles/pull/522#issuecomment-1950274371

**Review by GenShibe — APPROVED** [review]
LGTM 👍🏼

**Review by FrancoRav — APPROVED** [review]

**Review by alythical — APPROVED** [review]

**Review by TheMemeSniper — APPROVED** [review]

**Review by trinkey — APPROVED** [review]
superior default color

**Review by isabelroses — APPROVED** [review]

**Review by coldenate — APPROVED** [review]

**Review by RoootTheFox — APPROVED** [review]
lgtm!

**Review by AnubisNekhet — APPROVED** [review]

**Review by GitMuslim — APPROVED** [review]

**Review by BlankParticle — APPROVED** [review]

**Pull request merged**
