### PR TITLE
feat(chatgpt): highlightjs

### PR DESCRIPTION
**Pull request by aemogie**
Use catppuccin/highlightjs for the codeblocks. (With one minor change to match the code background and the container background)

### CODE REVIEW

**Comment by isabelroses** [comment]
Completes what https://github.com/catppuccin/userstyles/pull/158 set out to fix.

**Review by rubyowo — COMMENTED** [review]
importing it would really be nice, but this works as a temporary fix. let's wait for someone to test it first.

**Comment by ozwaldorf** [comment]
image

Looks like it's working great!

**Comment by rubyowo** [comment]
LGTM.

**Review by rubyowo — APPROVED** [review]

**Pull request merged**
