### PR TITLE
fix(chatgpt): fix new ui + accent colours

### LINKED ISSUE #303: Unthemed elements in the new ChatGPT layout
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:chatgpt

### Describe your problem.

OpenAI recently made some changes to the ChatGPT layout that have introduced some new elements that aren't themed correctly.

### Attach screenshots.

image
image

image
image

### What browser(s) are you seeing the problem on?

Firefox Developer Edition 120.0b8

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by aemogie**
## 🔧 What does this fix? 🔧

Fixes issues with the new UI
Adds accent colour options
Closes #303 

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [contributing guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/CONTRIBUTING.md).
- [x] I have updated the version appropriately in the `==UserStyle==` header of the `catppuccin.user.css` file.

### CODE REVIEW

**Comment by aemogie** [comment]
Need someone with ChatGPT plus to test this.

**Review by isabelroses — CHANGES_REQUESTED** [review]
Hello, whilst testing I noticed some issues.

<details>

image

By default these buttons should only be a different colour from the dropdown when on hover
image


</details>

**Comment by aemogie** [comment]
Doesn't fix
- ToS update message ToS update message
- and plugin search
plugin search

mentioned in #303

**Comment by isabelroses** [comment]
Hi @aemogie,

I'm just going to put this on pause until https://github.com/catppuccin/userstyles/pull/323 is merged as this may result in you having to make some changes to your code.

Thanks for your patience.

**Comment by isabelroses** [comment]
Hi @aemogie,

Now #323 has been merged, I am happy to take a look at this but before that. I notice some merge errors if this could be handled first, I'll take a look at this port.

Thanks again for your work and patience.

**Review by isabelroses — APPROVED** [review]

**Comment by isabelroses** [comment]
Thanks for the PR and your patience.

**Pull request merged**
