### PR TITLE
fix(twitter): add x.com url

### PR DESCRIPTION
**Pull request by nonetrix**
Adds the URL x.com since the URL is being changed

## 🔧 What does this fix? 🔧

Fixes the URL since it has been updated or is being updated

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [contributing guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/CONTRIBUTING.md).
- [x] I have updated the version appropriately in the `==UserStyle==` header of the `catppuccin.user.css` file.

### CODE REVIEW

**Comment by nonetrix** [comment]
Xhanks Xlon Xusk xery xool

**Comment by nonetrix** [comment]
Should the folder and etc. Be renamed to X or nah? What is everyones take now that the URL has changed?

**Comment by nonetrix** [comment]
Closing in favor of #894

**Review by isabelroses — APPROVED** [review]

**Comment by nonetrix** [comment]
Please review #898

**Pull request merged**
