### PR TITLE
refactor(nixos.wiki): rewrite

### PR DESCRIPTION
**Pull request by somerand0mcat**
## 🔧 What does this fix? 🔧
as said in the title
image
image

## 🗒 Checklist 🗒

- [X] I have read and followed Catppuccin's [contributing guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/CONTRIBUTING.md).
- [X] I have updated the version appropriately in the `==UserStyle==` header of the `catppuccin.user.css` file.

### CODE REVIEW

**Comment by uncenter** [comment]
As per https://github.com/catppuccin/userstyles/issues/781 this website is basically deprecated. I would prefer to replace this nixos.wiki with a new user style for wiki.nixos.org.

**Comment by somerand0mcat** [comment]
> As per #781 this website is basically deprecated. I would prefer to replace this nixos.wiki with a new user style for wiki.nixos.org.

but who'll maintain the new userstyle?
i cant be maintainer because im banned from the discord

**Comment by uncenter** [comment]
There doesnt need to be a maintainer.

**Comment by uncenter** [comment]
Why are you contributing to all of these userstyles anyway?

**Comment by somerand0mcat** [comment]
> Why are you contributing to all of these userstyles anyway?

because i want the users to have a nice experience

**Comment by somerand0mcat** [comment]
also because i like coding html/css too

**Pull request closed without merging**
