### PR TITLE
ci: add deploy website workflow

### PR DESCRIPTION
**Pull request by sgoudham**
First time writing CI to call a reusable workflow, lets see if it works first try :D 

Depends on https://github.com/catppuccin/catppuccin/pull/2322

### CODE REVIEW

**Review by isabelroses — APPROVED** [review]
LGTM ig

**Review by backwardspy — APPROVED** [review]
yeah... i suppose

**Review by nullishamy — APPROVED** [review]
sure

**Review by thelooter — APPROVED** [review]
cool i guess

**Review by nullishamy — COMMENTED** [review]
Lets get this merged!

**Comment by TuxGamer** [comment]
LGTM lets do this

**Pull request merged**
