### PR TITLE
build(lint): use native stylelint config resolution

### PR DESCRIPTION
**Pull request by uncenter**
Prevent errors on custom elements in #346, see https://github.com/catppuccin/userstyles/pull/346#issuecomment-1820213474.

### CODE REVIEW

**Comment by nekowinston** [comment]
I really liked the added typo protection that `selector-type-no-unknown` added, and I think it's rare enough where a workaround for each userstyle isn't that much effort. I'll push what I came up with.

**Comment by nekowinston** [comment]
Lichess lint passes for me when I create `./styles/lichess/.stylelintrc.json` with:
```json
{
  "rules": {
    "selector-type-no-unknown": [
      true,
      { "ignore": ["signal", "index", "fill"] }
    ]
  }
}
```

**Comment by nekowinston** [comment]
[8ed27aa](https://github.com/catppuccin/userstyles/pull/350/commits/8ed27aa4dbc29190a38b7b72dfa9dd984eae3702) works but this really isn't getting any more maintainable.
Luckily it turned out that turning on [`nodeModulesDir`](https://docs.deno.com/runtime/manual/getting_started/configuration_file#nodemodulesdir) and not passing in `config` into `stylelint.lint` does everything we want for us.

The config file will have to include an `extends` to the repo root, compared to the previous impl:
```json
{
  "extends": "../../.stylelintrc.js",
  "rules": {
    "selector-type-no-unknown": [true, { "ignore": ["signal", "index", "fill"] }]
  }
}
```

**Review by nekowinston — APPROVED** [review]
Think this should do it.

**Comment by uncenter** [comment]
That's way better, thanks!

**Pull request merged**
