### PR TITLE
fix(brave): settings page

### PR DESCRIPTION
**Pull request by coopw1**
## 🔧 What does this fix? 🔧
Fixes unthemed elements on settings page

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [contributing guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/CONTRIBUTING.md).
- [x] I have updated the version appropriately in the `==UserStyle==` header of the `catppuccin.user.css` file.

### CODE REVIEW

**Comment by coopw1** [comment]
weeee

**Review by uncenter — CHANGES_REQUESTED** [review]
Screenshot 2023-11-20 at 23 01 41 (Arc)
Screenshot 2023-11-20 at 23 02 07 (Arc)

🤨

**Comment by coopw1** [comment]
> 🤨
gaa whoops, thanks for reminding

**Review by ndsboy — APPROVED** [review]
looks great, haven't checked the settings page in a while 😄 thank you for your contribution!

**Pull request merged**
