### PR TITLE
fix(tldraw): sticky note + white pen color

### PR DESCRIPTION
**Pull request by GenShibe**
## 🔧 What does this fix? 🔧
fixes the colors of the sticky note not being themed as well as add support for their secret white pen color

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [contributing guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/CONTRIBUTING.md).
- [x] I have updated the version appropriately in the `==UserStyle==` header of the `catppuccin.user.css` file.

### CODE REVIEW

**Review by uncenter — CHANGES_REQUESTED** [review]
New colors are not themed, haven't checked the rest.

**Review by uncenter — CHANGES_REQUESTED** [review]
Light gray rectangle outline is unthemed in light mode, dark blue rectangle outline is unthemed in dark mode.

**Comment by sgoudham** [comment]
Hey @GenShibe :wave: 

Where is this PR currently at? I see uncenter added a label but you removed it afterwards. is it good to be re-reviewed now?

**Comment by uncenter** [comment]
> Hey @GenShibe 👋
> 
> Where is this PR currently at? I see uncenter added a label but you removed it afterwards. is it good to be re-reviewed now?

It half fixes some of the issues but I don't think @GenShibe wanted to complete it. It's been on my todo list, I'll close for now and come back to it later.

**Comment by sgoudham** [comment]
Ah right, I mean you can leave it open since you want to come back to it. I was just commenting since it was odd to see the label being removed without any further commits/discussion on GitHub.

**Pull request closed without merging**
