### PR TITLE
fix(treewide): enforce `catppuccin/userstyles` code standards

### PR DESCRIPTION
**Pull request by isabelroses**
As of the merge of https://github.com/catppuccin/userstyles/pull/318, where we started the process of creating standardize code between the userstyles.

The purpose of this PR is to continue that process and enforce more of these standard practices between our userstyles.

### CODE REVIEW

**Review by TheMemeSniper — APPROVED** [review]

**Review by ryanccn — APPROVED** [review]

**Review by uncenter — APPROVED** [review]

**Review by uncenter — APPROVED** [review]

**Review by r58Playz — APPROVED** [review]

**Review by Tnixc — APPROVED** [review]

**Review by alaidriel — APPROVED** [review]

**Review by lucasmelin — APPROVED** [review]

**Review by BlankParticle — APPROVED** [review]

**Review by GenShibe — APPROVED** [review]
sadly there's no disapprove selection becasue i wanted to select that and see what happens LOL, but i approve :p

**Comment by nekowinston** [comment]
Now it's time for the visual reviews - please double check if your styles are still working, if we had to change a lot.

**Comment by isabelroses** [comment]
Hello @catppuccin/userstyles-maintainers,

Thanks for everyone's patience with this repo, I understand this is not exactly the most stable or steady repo/project. But in order to make this project easier to maintain we introduced a linted and me and @nekowinston (thanks by the way) along with the help of @uncenter have been going through the code and cleaning it up.

However, we realise this may cause regressions in the userstyles that everyone has taken so long to develop, so please take your time reviewing the code.

Thank you all.

**Review by nekowinston — APPROVED** [review]
I just checked the stylesheets I maintain (invidious, nixos.wiki, substack) these LGTM.

**Review by justTOBBI — COMMENTED** [review]
Changes on "my" ports look good, thanks for your work once again :)

**Review by soya-daizu — APPROVED** [review]

**Review by GitMuslim — APPROVED** [review]

**Review by jn-sena — APPROVED** [review]

**Comment by isabelroses** [comment]
I can't exactly approve my own PR, but all the regressions, have been fixed within my ports. 👍

**Pull request merged**
