### PR TITLE
fix(github): regex

### LINKED ISSUE #422: Github userstyle regex fails to match certain users and orgs
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:github

### Describe your problem.

The regex for github userstyle fails to match users and organizations whose name starts with `home`, `marketplace`, etc. I discovered this on https://github.com/homebridge, any repo under their org is not themed.

image
As you can see, the regex used to exclude `/home` also excludes `homebridge`

### Attach screenshots.

image

### What browser(s) are you seeing the problem on?

Microsoft Edge 120.0.2210.91

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by nekowinston**
Closes #422

https://regexr.com/7pqa8

### CODE REVIEW

**Review by BlankParticle — CHANGES_REQUESTED** [review]
Fixes the issue I mentioned,
when we are at rewriting the regex we should also exclude https://github.com/features

**Review by BlankParticle — APPROVED** [review]
LGTM, I think we can merge it

**Comment by nekowinston** [comment]
I'd prefer being explicit over composition with `\/foo|\/bar` vs `\/(foo|bar)`, the 2nd gets super messy

**Comment by isabelroses** [comment]
> I'd prefer being explicit over composition with `\/foo|\/bar` vs `\/(foo|bar)`, the 2nd gets super messy

This makes sense to me.

**Pull request merged**
