### PR TITLE
refactor(brave-search): rewrite

### LINKED ISSUE #713: Brave Search is no longer themed
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:brave-search

### Describe your problem.

Brave Search is no longer themed at all.

### Attach screenshots.

image

### What browser(s) are you seeing the problem on?

Firefox v124.0.1

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by uncenter**
## 🔧 What does this fix? 🔧

Closes #713. Seems like a bunch of things changed and the vars weren't right anymore, started changing and decided to start fresh.

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [contributing guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/CONTRIBUTING.md).
- [x] I have updated the version appropriately in the `==UserStyle==` header of the `catppuccin.user.css` file.

### CODE REVIEW

**Comment by uncenter** [comment]
@ndsboy feel free to take over this PR seeing as you are the actual maintainer :D

**Comment by ndsboy** [comment]
Hi @uncenter, sorry for the late reply, GitHub did not send me a notification for this one...
Thank you very much for your rewrite, the base looks great, however I felt like changing the container color to base and adding a more prominent border aligns more with the default brave design and with the other designs.

I've also changed up the icon code a bit, so now the icon and tab color changes depending on your accent color (like reddit or youtube).

Please let me know what you think of these changes :)

**Comment by uncenter** [comment]
> Hi @uncenter, sorry for the late reply, GitHub did not send me a notification for this one... Thank you very much for your rewrite, the base looks great, however I felt like changing the container color to base and adding a more prominent border aligns more with the default brave design and with the other designs.
> 
> I've also changed up the icon code a bit, so now the icon and tab color changes depending on your accent color (like reddit or youtube).
> 
> Please let me know what you think of these changes :)

No worries! It is still marked as a draft pull request which is why you didn't get a notification for this. I totally agree with your changes (and this is your userstyle anyway xD)!

**Review by ndsboy — APPROVED** [review]
LGTM, thank you @uncenter for your contribution!

**Pull request merged**
