### PR TITLE
fix(youtube): shorts progress bar

### PR DESCRIPTION
**Pull request by somerand0mcatt**
## 🔧 What does this fix? 🔧
Fixes the unthemed progressbar on shorts.

<details>
<summary>Preview</summary>

</details>

## 🗒 Checklist 🗒

- [X] I have read and followed Catppuccin's [contributing guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/CONTRIBUTING.md).
- [X] I have updated the version appropriately in the `==UserStyle==` header of the `catppuccin.user.css` file.

### CODE REVIEW

**Comment by somerand0mcatt** [comment]
im going to draft this pull request because both isabel and uncenter is on break and can't really review PRs, going to reopen it once the break is over

**Comment by uncenter** [comment]
What? Neither of us is "on break" and I'm not sure how a draft PR makes it any different.

**Comment by somerand0mcatt** [comment]
> What? Neither of us is "on break" and I'm not sure how a draft PR makes it any different.

huh, i thought you were on break because you stopped reviewing prs for a while

**Comment by uncenter** [comment]
I've opened 6 PRs myself in the past 3 days and closed multiple others, as well as provided updated reviews. But again, that aside, making your PRs drafts does absolutely nothing. All it does is incorrectly signal that *you* are not ready for this to be reviewed. Please leave a thumbs up if you understand.

**Review by uncenter — APPROVED** [review]

**Pull request merged**
