### PR TITLE
fix(youtube): unthemed text

### PR DESCRIPTION
**Pull request by somerand0mcat**
## 🔧 What does this fix? 🔧
as said in the title
image
image

## 🗒 Checklist 🗒

- [X] I have read and followed Catppuccin's [contributing guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/CONTRIBUTING.md).
- [X] I have updated the version appropriately in the `==UserStyle==` header of the `catppuccin.user.css` file.

### CODE REVIEW

**Comment by isabelroses** [comment]
do you mind pointing to where this is.

**Comment by isabelroses** [comment]
> look at the difference between the text at the bottom

I ment where you found the issue.

**Comment by isabelroses** [comment]
> > I ment where you found the issue.
> 
> i just checked the description of a short and found unthemed text

then can we move it down to be with the rest of the shorts code https://github.com/somerand0mcat/userstyles/blob/bbc25a3071014b7dda7b0d852b78a6daf14ae30c/styles/youtube/catppuccin.user.css#L899

**Comment by somerand0mcat** [comment]
i moved it

**Review by isabelroses — APPROVED** [review]

**Pull request merged**
