### PR TITLE
ci: consolidate format & generate workflows

### PR DESCRIPTION
**Pull request by uncenter**
Fixes the race condition between the two workflows committing to the repository by combining them into one. Requires switching the commit workflow from `stefanzweifel/git-auto-commit-action` to `EndBug/add-and-commit` because the former lacks a way to disable pushing the commit immediately.

### CODE REVIEW

**Review by sgoudham — APPROVED** [review]
Looks fine, guess we won't really know until it's live.

**Review by sgoudham — CHANGES_REQUESTED** [review]
Actually, just caught something. We can remove the if conditions on the add and commit action and move it to the git push step? Since that's what we want to prevent when it's running on a fork.

**Comment by uncenter** [comment]
Right. Shouldn't we move it to be an if statement for the whole job? Just don't run any of it? Why would we do that only on individual steps?

**Comment by uncenter** [comment]
Ah, turns out we don't have the `env` context in a` jobs.<id>.if`. Shoot.

**Review by sgoudham — APPROVED** [review]

**Pull request merged**
