### PR TITLE
feat(akkoma): init

### PR DESCRIPTION
**Pull request by somerand0mcatt**
## 🎉 Theme for [Akkoma](https://akkoma.social/) 🎉
image
Akkoma is a small microblogging platform, aka the cooler pleroma

## 💬 Additional Comments 💬
N/A

## 🗒 Checklist 🗒

- [X] I have read and followed Catppuccin's [submission guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/userstyle-creation.md).
- [X] I have made a new directory underneath `/styles/<name-of-website>` containing the contents of the [`/template`](https://github.com/catppuccin/userstyles/blob/main/template/) directory.
  - [X] I have ensured that the new directory is in **lower-kebab-case**.
  - [X] I have followed the template and kept the preprocessor as [LESS](https://lesscss.org/#overview).
- [X] I have made sure to update the
      [`userstyles.yml`](https://github.com/catppuccin/userstyles/blob/main/scripts/userstyles.yml)
      file with information about the new userstyle.
- [X] I have included the following files:
  - [X] `catppuccin.user.css` - all the CSS for the userstyle, based on the
        template.
  - [X] `preview.webp` - composite image of all four individual flavor screenshots (taken with the default accent color of mauve) stitched together, generated via [Catwalk](https://github.com/catppuccin/catwalk).

### CODE REVIEW

**Comment by uncenter** [comment]
I believe Akkoma has native theme support? I'm also not sure how we should deal with adding new userstyles that you can't maintain. Going to put this on pending for now.

**Comment by somerand0mcatt** [comment]
> I believe Akkoma has native theme support?

I think it does but that would probably need its own repo
> I'm also not sure how we should deal with adding new userstyles that you can't maintain. Going to put this on pending for now.

huh, someone told me that I can submit ports without maintaining them

**Comment by uncenter** [comment]
> huh, someone told me that I can submit ports without maintaining them

I don't want to add additional tech debt to the repo. I believe that was a special case where you were continuing on someone else's work.

**Comment by somerand0mcatt** [comment]
> I don't want to add additional tech debt to the repo. I believe that was a special case where you were continuing on someone else's work.

yeah, im pretty sure that was the pythonanywhere PR where i used trinkey's work

**Comment by somerand0mcatt** [comment]
im going to close this pull request because after i did some searching i found out there was already a catppuccin akkoma port made [by amy](https://github.com/nullishamy/ctp-akkoma) and a user on the [akkoma.dev gitea](https://akkoma.dev/tea/akkoma-fe-themes/src/branch/main/out), which appeared to be a bit better than the userstyle i made, i also can't maintain the userstyle after its merged so..

**Pull request closed without merging**
