### PR TITLE
feat(skiff): init

### PR DESCRIPTION
**Pull request by coopw1**
## 🎉 Theme for Skiff🎉
Skiff is an open source, privacy based email service. It has a very generous free tier, and has no ads.
catwalk

## 💬 Additional Comments 💬
First time doing this! Hopefully it's alright lol

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [submission guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/userstyle-creation.md).
- [x] I have made a new directory underneath `/styles/<name-of-website>` containing the contents of the [`/template`](https://github.com/catppuccin/userstyles/blob/main/template/) directory.
  - [x] I have ensured that the new directory is in **lower-kebab-case**.
  - [x] I have followed the template and kept the preprocessor as [LESS](https://lesscss.org/#overview).
- [x] I have made sure to update the
      [`userstyles.yml`](https://github.com/catppuccin/userstyles/blob/main/src/userstyles.yml)
      file with information about the new userstyle.
- [x] I have included the following files:
  - `catppuccin.user.css` - all the CSS for the userstyle, based on the
    template.
  - `assets/mocha.webp`, `assets/macchiato.webp`, `assets/frappe.webp` and
    `assets/latte.webp` - individual screenshots of the themed website, in all 4
    Catppuccin flavors.
  - `catwalk.webp` - image of all individual screenshots stitched together,
    generated via [catwalk](https://github.com/catppuccin/toolbox#-catwalk).

### CODE REVIEW

**Review by isabelroses — CHANGES_REQUESTED** [review]
Hai there, 
Thanks for this PR. Before I do a proper review can you please go over the linter warnings and correct the errors, thank you.

**Review by coopw1 — COMMENTED** [review]
Alrightt, I think that should fix it?

**Comment by uncenter** [comment]
You've already finished the userstyle but I would recommend trying to leave comments wherever you can. The classes you are using as selectors aren't informative of what they select, which makes it more difficult for you to maintain it in the future!

**Comment by coopw1** [comment]
working on it! I found a few spots that I missed the first time few as well, gonna fix those up

**Review by coopw1 — COMMENTED** [review]
I ended up just changing it to use the built in vars, should be much better now

**Comment by uncenter** [comment]
Looks great! Nice comments as well. I don't think you need to bump the version to `0.0.2` though since it hasn't been merged/released yet.

**Review by coopw1 — COMMENTED** [review]
Alright, thanks guys! let me know if I missed anything

**Review by uncenter — APPROVED** [review]

**Review by isabelroses — APPROVED** [review]

**Comment by coopw1** [comment]
oooh- just realized that by switching to vars it automatically did most of the drive/calendar/note apps. I might go ahead and finish up the whole website at some point soon

**Pull request merged**
