### PR TITLE
feat(stack-overflow): support more stack exchange sites

### PR DESCRIPTION
**Pull request by uncenter**
## 🔧 What does this fix? 🔧

Extends support to other Stack Exchange sites (https://stackexchange.com/sites). Also adds more styling to the cookie management popup.

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [contributing guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/CONTRIBUTING.md).
- [x] I have updated the version appropriately in the `==UserStyle==` header of the `catppuccin.user.css` file.

### CODE REVIEW

**Comment by uncenter** [comment]
@NoPlagiarism here you go!

**Review by isabelroses — APPROVED** [review]

**Comment by NoPlagiarism** [comment]
There's one little problem. It's not all off StackExchange sites

- [ ] askubuntu.com
- [ ] stackapps.com

Thanks for doing this!

**Comment by uncenter** [comment]
> There's one little problem. It's not all of StackExchange sites
> 
> * [ ]  askubuntu.com
> * [ ]  stackapps.com
> 
> Thanks for doing this!

Yeah I know I just did the top 5 since I don't have time to do all 180 something! I'll do those two though.

**Comment by uncenter** [comment]
@NoPlagiarism looks good now or?

**Pull request merged**
