### PR TITLE
ci: automatically sync maintainers in the team

### LINKED ISSUE #112: Automate additions/removals to `@userstyles-maintainers`
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your issue.

Currently, adding and removing maintainers within `current-maintainers` in the `userstyles.yaml` does not update `@userstyles-maintainers` team.

This is frustrating because the `CODEOWNERS` file expects that all listed users have write permissions. Without some form of automation, members will have to be manually added and removed which is definitely something we want to avoid as this repository grows in popularity. 

We should utilise GitHub's GraphQL API to automatically update the entire team based on the current state of `current-maintainers` in our CI workflows.

### Acceptance Criteria

- [ ] additions/removals to `current-maintainers` should be reflected in the `@userstyles-maintainers` team

### PR DESCRIPTION
**Pull request by rubyowo**
Closes #112

### CODE REVIEW

**Comment by rubyowo** [comment]
wait i didn't add an action oops

**Comment by rubyowo** [comment]
oh no GITHUB_TOKEN

**Review by nekowinston — APPROVED** [review]
ig

**Comment by nekowinston** [comment]
I'll convert to a draft until @sgoudham updates the GitHub token, since he owns the secret.

**Review by sgoudham — APPROVED** [review]
Updated the token to allow additions/removals to the userstyles team. 
In the spirit of @nekowinston, looks alright I guess!

**Pull request merged**
