### PR TITLE
refactor(gmail): rewrite

### LINKED ISSUE #414: Gmail Broken
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:gmail

### Describe your problem.

Styles Off
Using Stylus

### Attach screenshots.

image

### What browser(s) are you seeing the problem on?

Chrome 120.0.6099.129 (Official Build) (64-bit) 

### Any additional comments?

_No response_

### LINKED ISSUE #870: gmail: Assumption of a base dark-mode theme
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:gmail

### Describe your problem.

Currently, the gmail theme makes an assumption (requirement?) that a base "dark mode" theme is already selected, which means certain elements will not display properly if the base gmail theme is light. There are specific situations where you *cannot* apply a dark mode theme to a gmail inbox (such as a delegated inbox, or some enterprise environments) and it would be nice if things worked regardless of the base theme selected. I realize this is annoying as some of the things that do not display properly are images, but I hear tell of dark CSS magic to get them to display properly. Bit of an edge case for sure, but figured I would report as maybe someone a bit more knowledgeable than myself would be able to fix it up quick enough.

Examples below do not cover all instances of this, but if it's helpful, I can try to provide screenshots of things as I come across them.  Most are fairly obvious when you have a light mode theme selected. #864 just recently merged fixed a few of these I had noticed and had local patches for, but wanted to raise the larger concern for tracking either way.

Thanks to everyone for all their hard work, and let me know if any additional information is helpful!

### Attach screenshots.

**Example when a Dark Mode theme is selected as base:**
Section titles:
image

Attachment icon:
image

**Example when a Light Mode theme is selected as a base:**
Section titles:
image

Attachment icon:
image

### What browser(s) are you seeing the problem on?

Chrome 124.0.6367.63

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by uncenter**
Probably closes #414, closes #870. Adds myself as maintainer for the Gmail userstyle and rewrites it from scratch.

- [x] Advanced filters
- [x] Label menu modal
	- [x] New label input
- [x] Settings
- [x] Compose mail window
- [x] Tooltips
- [x] Gmail logo

### CODE REVIEW

**Comment by uncenter** [comment]
Note to self: undo icon filter that overrides label colors:
image

**Comment by r58Playz** [comment]
image
Sidebar unthemed.
image
Google Chat status unthemed. Dropdown too.
image
Important unthemed.
image
Quick settings unthemed.
image
Labels unthemed.
image
Divider unthemed.
image
IMAP status unthemed.
image
Hover on mail unthemed.
image
Attachment preview unthemed.
image
Trash warning unthemed.

**Review by isabelroses — COMMENTED** [review]
As far as I can tell this only fixes issues, and breaks nothing. Really impressive

**Review by isabelroses — DISMISSED** [review]

**Comment by uncenter** [comment]
@r58Playz fixed the important indicator, labels settings page, trash warning, hover on mail box shadow, and the attachment chips. I could not theme the IMAP status (requires lengthy setup) and Google Chat/Meet sidebar and dropdowns (don't have on my Gmail account ig). Quick settings has been left intentionally unthemed for now, will get to it later.

**Review by r58Playz — APPROVED** [review]

**Pull request merged**
