### PR TITLE
feat(youtube): new player ui

### PR DESCRIPTION
**Pull request by isabelroses**
## 🔧 What does this fix? 🔧

Fixes new player ui

Old
image

New
image

i know what a crazy fix

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [contributing guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/CONTRIBUTING.md).
- [x] I have updated the version appropriately in the `==UserStyle==` header of the `catppuccin.user.css` file.

### CODE REVIEW

**Review by uncenter — CHANGES_REQUESTED** [review]
Version needs to be bumped.

**Comment by isabelroses** [comment]
I'm so out of tocuh

**Comment by uncenter** [comment]
> I'm so out of tocuh

You fell off

**Review by uncenter — APPROVED** [review]

**Comment by isabelroses** [comment]
> You fell off

So real

Also yes i bumped to x.1.x because I hate vers like x.x.100000

**Comment by uncenter** [comment]
Fixes the short video player for me, I wasn't seeing the other updated UI in the first place but I'll assume it works.

**Pull request merged**
