### PR TITLE
refactor(stylus): use nesting wherever possible, simplify selectors

### PR DESCRIPTION
**Pull request by uncenter**
## 🔧 What does this fix? 🔧

Various fixes

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [contributing guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/CONTRIBUTING.md).
- [x] I have updated the version appropriately in the `==UserStyle==` header of the `catppuccin.user.css` file.

### CODE REVIEW

**Review by isabelroses — APPROVED** [review]
could be worth leaving a comment on the codemirror stuff that if they ever update codemirror we can import that

**Comment by uncenter** [comment]
> could be worth leaving a comment on the codemirror stuff that if they ever update codemirror we can import that

Wdym?

**Comment by isabelroses** [comment]
> > could be worth leaving a comment on the codemirror stuff that if they ever update codemirror we can import that
> 
> Wdym?

we could import the [codemirror port](https://github.com/catppuccin/codemirror) but that uses codemirror 5 i believe stylus uses codemirror 4.

**Comment by uncenter** [comment]
> > > could be worth leaving a comment on the codemirror stuff that if they ever update codemirror we can import that
> > 
> > 
> > Wdym?
> 
> we could import the [codemirror port](https://github.com/catppuccin/codemirror) but that uses codemirror 5 i believe stylus uses codemirror 4.

What file do we import from there?

**Comment by isabelroses** [comment]
> > > > could be worth leaving a comment on the codemirror stuff that if they ever update codemirror we can import that
> > > 
> > > 
> > > Wdym?
> > 
> > 
> > we could import the [codemirror port](https://github.com/catppuccin/codemirror) but that uses codemirror 5 i believe stylus uses codemirror 4.
> 
> What file do we import from there? The compiled themes won't work here.

really? I thought this would work https://github.com/catppuccin/codemirror/blob/main/themes/mocha.css

**Comment by uncenter** [comment]
> > > > > could be worth leaving a comment on the codemirror stuff that if they ever update codemirror we can import that
> > > > 
> > > > 
> > > > Wdym?
> > > 
> > > 
> > > we could import the [codemirror port](https://github.com/catppuccin/codemirror) but that uses codemirror 5 i believe stylus uses codemirror 4.
> > 
> > 
> > What file do we import from there? The compiled themes won't work here.
> 
> really? I thought this would work [catppuccin/codemirror@`main`/themes/mocha.css](https://github.com/catppuccin/codemirror/blob/main/themes/mocha.css?rgh-link-date=2024-08-19T18%3A55%3A37Z)

That has `cm-s-ctp-mocha` as the main selector, not `cm-s-default`. I do technically maintain Codemirror so I can try making a version selecting the default theme?

**Review by GitMuslim — APPROVED** [review]

**Pull request merged**
