### PR TITLE
feat(tabnews): init

### PR DESCRIPTION
**Pull request by Guaxinim5573**
## 🎉 Theme for [TabNews](https://tabnews.com.br) 🎉

[TabNews.com.br](https://tabnews.com.br) is a website focused around the community of the Brazil's tech field, aimed at debates and exchange of knowledge through publications and comments created by the users themselves.

<details><summary>Latte</summary></details>
<details><summary>Frappe</summary></details>
<details><summary>Macchiato</summary></details>
<details><summary>Mocha</summary></details>

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [submission guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/userstyle-creation.md).
- [x] I have made a new directory underneath `/styles/<name-of-website>` containing the contents of the [`/template`](https://github.com/catppuccin/userstyles/blob/main/template/) directory.
  - [x] I have ensured that the new directory is in **lower-kebab-case**.
  - [x] I have followed the template and kept the preprocessor as [LESS](https://lesscss.org/#overview).
- [x] I have made sure to update the
      [`userstyles.yml`](https://github.com/catppuccin/userstyles/blob/main/scripts/userstyles.yml)
      file with information about the new userstyle.
- [x] I have included the following files:
  - `catppuccin.user.css` - all the CSS for the userstyle, based on the
    template.
  - `assets/mocha.webp`, `assets/macchiato.webp`, `assets/frappe.webp` and
    `assets/latte.webp` - individual screenshots of the themed website, in all 4
    Catppuccin flavors.
  - `catwalk.webp` - image of all individual screenshots stitched together,
    generated via [Catwalk](https://github.com/catppuccin/toolbox/tree/main/catwalk#readme).

### CODE REVIEW

**Review by isabelroses — APPROVED** [review]
Wow, it looks amazing. Great work.

**Comment by uncenter** [comment]
These blue and green squares look unthemed:

Screenshot 2024-03-03 at 19 20 52 (Arc)

**Comment by Guaxinim5573** [comment]
> These blue and green squares look unthemed:
> 
> Screenshot 2024-03-03 at 19 20 52 (Arc)

Since they represent something on the website (in this case, TabCoins and TabCash) I didn't think about themeing them. Is it really necessary to theme them?

**Comment by uncenter** [comment]
Yes.

**Comment by uncenter** [comment]
Screenshot 2024-03-03 at 20 53 10 (Arc)
What's going on with the corners of the preview images?

**Comment by Guaxinim5573** [comment]
I'm using [catwalk](https://github.com/catppuccin/toolbox/tree/main/catwalk) to generate the final `catwalk.webp` image and it generates with rounded corners. Other images are fine.

**Comment by uncenter** [comment]
What command are you using for it?

**Comment by Guaxinim5573** [comment]
> What command are you using for it?

`catwalk latte.webp frappe.webp macchiato.webp mocha.webp -o catwalk.webp`

**Comment by uncenter** [comment]
> > What command are you using for it?
> 
> `catwalk latte.webp frappe.webp macchiato.webp mocha.webp -o catwalk.webp`

Huh where did you install catwalk from? Also FYI you don't need to pass in `latte.webp frappe.webp macchiato.webp mocha.webp` since those are the default files :)

**Comment by Guaxinim5573** [comment]
Latest release catwalk version (catppuccin-catwalk 1.2.0). Installed using [Archlinux's AUR](https://aur.archlinux.org/packages/catwalk-bin). Using `-r 0` removes the rounded corners, I can do that.

**Comment by uncenter** [comment]
I don't think there should be any sort of rounded corners by default?

**Comment by Guaxinim5573** [comment]
> I don't think there should be any sort of rounded corners by default?

Looks like catwalk always adds rounded corners by default. See https://github.com/catppuccin/toolbox/blob/20d40479bbf3345f2b1038c736a07ccb4c6efda9/catwalk/src/lib.rs#L68

**Comment by uncenter** [comment]
Ah nevermind you are right, there is rounding by default :D how have I never noticed that! 😭

**Review by uncenter — APPROVED** [review]

**Comment by Guaxinim5573** [comment]
I removed the scrollbar of the website to take better screenshots and it looks good now.
catwalk

**Review by uncenter — CHANGES_REQUESTED** [review]
Light/dark sun/moon toggle unthemed when logged out:
Screenshot 2024-03-04 at 00 09 26 (Arc)
Screenshot 2024-03-04 at 00 09 22 (Arc)

Borders of this input search box looks wrong compared to the unthemed site (the corners are missing?):
Screenshot 2024-03-04 at 00 10 12 (Arc)

Create new account disabled button unthemed:
Screenshot 2024-03-04 at 00 12 27 (Arc)

**Comment by Guaxinim5573** [comment]
> Light/dark sun/moon toggle unthemed when logged out
Moon icon is actually themed with sky.

**Review by isabelroses — APPROVED** [review]

**Comment by uncenter** [comment]
Uh I don't believe this was ready for merging? The changes I mentioned has not been resolved.

**Comment by Guaxinim5573** [comment]
> Uh I don't believe this was ready for merging? The changes I mentioned has not been resolved.

Indeed. I also found some unstyled stuff on other pages. I will create a new PR with changes in a few days.

**Comment by uncenter** [comment]
Thank you! Sorry about the confusion.

**Pull request merged**
